### ISSUE TITLE
[bug] crash when planting rainberry bush

### ISSUE THREAD

**Issue by Poooppy** [ix0rai/bodaciousberries#50]
I got this crash when i tried to replant this berries into the ground.

> CrashIllegalArgumentException: Cannot set property class_2754{name=type, clazz=class net.minegate.fr.moreblocks.block.enums.FernType, values=[default, plant]} as it does not exist in Block{bodaciousberries:rainberry_bush}

Full Error Details Link : https://bytebin.lucko.me/DNzw6jeKtI

**Comment by eristhea** [comment]
This issue is caused by moreblocks, and can't be fixed on my end.
You can see the report at https://github.com/MrFantiVideo/MineGate/issues/26
In that issue there's a [preview version](https://libraries.minegate.fr/maven/net/minegate/fr/minegate-moreblocks/1.2.1-dev2/minegate-moreblocks-1.2.1-dev-2.jar) which *should* fix your issue

**Comment by eristhea** [comment]
@Poooppy can you please verify that this is fixed with the preview version?

**Comment by Poooppy** [comment]
> @Poooppy can you please verify that this is fixed with the preview version?

I just test with Preview version of minegate-moreblocks and it still not fixed yet.

Thank you so much for your reply ♥  I really love your mod 🥇 Great graphic + Lovely design ♥♥♥
And I apologies for my trouble.

**Comment by eristhea** [comment]
thank you so much for the compliments!
would you mind if I closed this issue, because it's up to minegate to fix?

**Comment by eristhea** [comment]
@Poooppy ping: could this be closed?

**Comment by Poooppy** [comment]
> @Poooppy ping: could this be closed?

SOrry for late reply 

No i dont mind and thank you ♥
